#!/bin/bash

score=0
max=0

echo "Positive Tests (files in tests/good/)"

for f in tests/good/*.py; do
    max=`expr $max + 1`;
    echo $f
    expected=tests/good/`basename $f .py`.out
    rm -f out
    if ./mini-python $f > out; then
	if cmp --quiet out $expected; then
	    score=`expr $score + 1`;
	else
	    echo "  FAILURE : bad output for $f"
	fi
    else
	echo "  FAILURE for the interpretation of $f"
    fi
done
echo

echo "Negative tests (files in tests/bad/)"

for f in tests/bad/*.py; do
    max=`expr $max + 1`;
    echo $f
    rm -f out
    if ./mini-python $f > out 2>&1; then
	echo "  FAILURE : the interpretation of $f should fail"
    else
        if grep -q "^error:" out; then
	    score=`expr $score + 1`;
        else
            echo "  FAILURE : should fail and print 'error'"
        fi
    fi
done

echo
percent=`expr 100 \* $score / $max`;
echo "Score: $score / $max tests, soit $percent%"
